class Constants:
    PROFILE_BUTTON: str
    RETURN_BACK_BUTTON: str
    RANDOM_MEME_BUTTON: str
    PERSONAL_MEMES_BUTTON: str
    RANDOM_PERSONAL_MEME_BUTTON: str
    MOST_POPUAR_MEME_BUTTON: str
    ADD_MEME_BUTTON: str
    LIKE_BUTTON: str
    DISLIKE_BUTTON: str
    NEXT_RANDOM_MEME_BUTTON: str
    SAVE_MEME_BUTTON: str

    PROFILE_QUERY: str
    RETURN_BACK_QUERY: str
    RANDOM_MEME_QUERY: str
    PERSONAL_MEMES_QUERY: str
    RANDOM_PERSONAL_MEME_QUERY: str
    MOST_POPUAR_MEME_QUERY: str
    ADD_MEME_QUERY: str
    LIKE_QUERY: str
    DISLIKE_QUERY: str
    NEXT_RANDOM_MEME_QUERY: str
    SAVE_MEME_QUERY: str

